version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pkg-update"
      include: "scope"
    assignees:
      - "jcarpe"
